# Generated by Django 3.1.6 on 2021-02-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinTransaction',
            new_name='CoinTransactions',
        ),
    ]
