# Generated by Django 3.1.6 on 2021-02-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20210201_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
