# Generated by Django 3.1.6 on 2021-02-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0004_auto_20210202_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
