version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  coin-web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/code/
    ports:
      - "8000:8000"
    environment:
      DB_PASS: ${DB_PASS}
      APP_LIST: "coin"
    depends_on:
      - db