version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  coin-web:
    extends:
      file: parent.yml
      service: web
    volumes:
      - ./app/coin:/code/coin
    ports:
      - "8000:8000"
    environment:
      APP_LIST: "coin"
    depends_on:
      - db
  payment-web:
    extends:
      file: parent.yml
      service: web
    volumes:
      - ./app/payment:/code/payment
    ports:
      - "8001:8000"
    environment:
      APP_LIST: "payment"
    depends_on:
      - db

