version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
  web-all:
    extends:
      file: parent.yml
      service: web
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  coin-web:
    extends:
      file: parent.yml
      service: web
    volumes:
      - ./app/coin:/code/coin
    ports:
      - "8001:8000"
    depends_on:
      - db

