# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      DB_PASS: testtest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 black
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
    - name: Test django
      run: |
        docker-compose run coin-web pipenv run python manage.py test > coin_test_result.txt
        docker-compose run payment-web pipenv run python manage.py test > payment_test_result.txt
    - name: Archive test results artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          coin_test_result.txt
          payment_test_result.txt
    - name: Lint with black
      run: |
        black .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count
    - name: git setting
      run: |
        git config --local user.email "t.nagashima.cog@gmail.com"
        git config --local user.name "2or3"
    - name: push
      run: |
        set +e
        git add .
        git commit -m"[Github action] formatted by black" -a
        git pull
        git push origin main
